### ISSUE TITLE
new options ?

### ISSUE THREAD

**Issue by NiKoCZ89** [parnexcodes/widevine-L3-WEB-DL-Script#15]
hello,

is there any chance to change a little bit script?

1. auto delete enc files after download video ?
2. update script that will choose and download auto best video/audio bitrate ?

**Comment by parnexcodes** [comment]
1). Remove the if condition in the end to delete files.
2). It already chooses best available bitrate.

**Comment by NiKoCZ89** [comment]
2. No it's not it download 96 instead 128 or dd5.1
but
1. What i need to delete ?
ty.
