### ISSUE TITLE
Traceback error using amazon with key.json

### ISSUE THREAD

**Issue by EliteAppleHacks** [parnexcodes/widevine-L3-WEB-DL-Script#16]
So i read the fix for lines 27 and 31 and i think the logic is fine so left it how it is. 

when running the script, i get

`Traceback (most recent call last):
  File "webdl.py", line 28, in <module>
    keys += f"--key {config[i]['kid']}:{config[i]['hex_key']} "
KeyError: 'kid'

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "webdl.py", line 32, in <module>
    keys += f"--key {config[i]['kid']}:{config[i]['hex_key']} "
KeyError: 'kid'`

Is my logic wrong? Attaching json file as well
[keys.zip](https://github.com/parnexcodes/widevine-L3-WEB-DL-Script/files/6948351/keys.zip)

**Comment by parnexcodes** [comment]
`for i in range(2, len(config)):`
