### ISSUE TITLE
Unable to extract course id

### ISSUE THREAD

**Issue by amirali1996** [parnexcodes/widevine-L3-WEB-DL-Script#17]
The script says that it cannot extract the course ID.
What's the problem?
![Capture](https://user-images.githubusercontent.com/88575553/128593047-a015bf9e-4cec-4313-8cda-e89ed9649cef.PNG)

**Comment by parnexcodes** [comment]
You need to provide mpd URL , not the udemy direct link .
There are tools available to download owned courses of udemy . I don't recommend using my script for udemy .

**Comment by NiKoCZ89** [comment]
I got same error with HBO HMAX it doesn't work ?

**Comment by parnexcodes** [comment]
> I got same error with HBO HMAX it doesn't work ?

HBO max has obfuscated their mpd URLs recently .
You can figure it out when you look inside mpd.
