### ISSUE TITLE
mpd_url 

### ISSUE THREAD

**Issue by BursztynowyCygan** [parnexcodes/widevine-L3-WEB-DL-Script#18]
I have keys.json but no mpd_url - HBO, D +
How download ?

**Comment by NiKoCZ89** [comment]
Z D+ tym
https://github.com/nilaoda/N_m3u8DL-CLI

hbo go raczej nie da rady.

jeżeli mpd detector nie wykrywa linku mpd lub cokolwiek to jest dupa...

jedynie pozostaje ipla/hbo działa, a player+ to nie wiem jakiś trailer z drm niby pobrało ale co z reszta tego nie powiem nie mam konta.

**Comment by BursztynowyCygan** [comment]
Podowiesz jak to odpalic ? przez CMD i skad ten link ogarnac z D + m3u8 ?
![image](https://user-images.githubusercontent.com/70627077/128615331-951a7331-2490-49ef-9776-811f43bc027e.png)

**Comment by NiKoCZ89** [comment]
https://freesoff.com/t/solved-how-to-download-from-disney-plus/39358
