### ISSUE TITLE
Error: 403 forbidden

### ISSUE THREAD

**Issue by Sentivet** [parnexcodes/widevine-L3-WEB-DL-Script#20]
I am getting error: 403 forbidden while trying to download mpd file. What to do for downloading?

**Comment by blackcraft987** [comment]
i have same probleme

**Comment by parnexcodes** [comment]
If you're able to download mpd file locally , make a gist on github and then use the raw url of that gist.

**Comment by Sentivet** [comment]
> I am getting error: 403 forbidden while trying to download mpd file. What to do for downloading?

https://gist.githubusercontent.com/Sentivet/316da74ba45adf159f9b78bfa3258e95/raw/d0362dc97b08fffffa584be004f9cb7d2b3d6335/video.mpd
