### ISSUE TITLE
webdl.py: error: unrecognized arguments: -m

### ISSUE THREAD

**Issue by bader515** [parnexcodes/widevine-L3-WEB-DL-Script#22]
**Hi,
Every time I run this script, I get "webdl.py: error: unrecognized arguments: -m {the MPD URL that I entered}".
There are no issues with the URL (I tested it using N_m3u8cli), and I tried other sites and still the same error.**

**Comment by parnexcodes** [comment]
The -m parameter only works with method-2 branch . I'll update the screenshot so people won't be confused.

**Comment by bader515** [comment]
I removed the -m parameter and I still get this error "webdl.py: error: unrecognized arguments: {mpd url}"
