### ISSUE TITLE
640kbps sound difference

### ISSUE THREAD

**Issue by Filtrattivo** [parnexcodes/widevine-L3-WEB-DL-Script#29]
The program works very well. Something happened that caught my attention. When the sounds are listed, there are those that say -1 and -0. What is the difference between -1 and -0?

![sss](https://user-images.githubusercontent.com/16515864/128922928-ef8a89a0-a05e-4551-9f1a-14166966ec50.PNG)

**Comment by BursztynowyCygan** [comment]
Please enter www

**Comment by Filtrattivo** [comment]
I did not understand what you said.

**Comment by BursztynowyCygan** [comment]
Please enter your keys.jeson I want to see if I also have the same quality

**Comment by NiKoCZ89** [comment]
As a default just use "0"
