### ISSUE TITLE
Linux

### ISSUE THREAD

**Issue by AndreVuillemot160** [parnexcodes/widevine-L3-WEB-DL-Script#3]
We need Linux edition.

**Comment by techno-arch** [comment]
the chrome extension it requires only works on windows

**Comment by Zachary24** [comment]
> the chrome extension it requires only works on windows

is there any way to make the python script compatible with linux/ubuntu? (not the extension)

**Comment by AndreVuillemot160** [comment]
> > the chrome extension it requires only works on windows
> 
> is there any way to make the python script compatible with linux/ubuntu? (not the extension)

I can give a try. Aria2, yt-dlp are in ubuntu and arch linux repos that's for sure, not sure about mkvmerge and mp4decryptor

**Comment by Zachary24** [comment]
i was able to install mp4decryptor using https://www.bento4.com/downloads/
and sudo apt-get install mkvtoolnix for mkvmerge

only problem is that it throws this now..
`congui@vmi403183:~/widevine-L3-WEB-DL-Script$ python3.9 webdl.py -o "jeje"
 _       ____________  ____  __       _____           _       __ 
| |     / / ____/ __ )/ __ \/ /      / ___/__________(_)___  / /_
| | /| / / __/ / __  / / / / /       \__ \/ ___/ ___/ / __ \/ __/
| |/ |/ / /___/ /_/ / /_/ / /___    ___/ / /__/ /  / / /_/ / /_  
|__/|__/_____/_____/_____/_____/   /____/\___/_/  /_/ .___/\__/  
                                                   /_/           

by parnex
Required files : yt-dlp.exe, mkvmerge.exe, mp4decrypt.exe, aria2c.exe

Selected MPD : https://bblf.play.cbsi.video/de/1.1YkJnDmEKxjbP1qgRad0K9YwJ1exBf9Qn3hYW0ap5ekM4bysW5nwtQGG3F3xiotTJYzJimd3jV5HSDIJG7Bx9WUVGcTSkB6pou1mAPe7EVZgOfOcFrvdNEK6rHZqn9eHMkZrG4rNYW2ugH
4eaHhe0KZibnxcstilpNnJPLDGtRk6bnI2W5rF8NMS1esQO3Nx3E43CKDwS1rakWfpKs8LeTpgO2PyKcOwIdDqFgBsP588ALjbCZNrIq6SgwhWV6qvSwH8rI6GKRZmYw7CQX2aaYG82NTzUAq/manifest.mpd#s=14400

WARNING: --downloader-args given without specifying name. The arguments will be given to all external downloaders
[generic] manifest: Requesting header
WARNING: [generic] Falling back on generic information extractor.
[generic] manifest: Downloading webpage
[generic] manifest: Extracting information
[info] manifest: Downloading 1 format(s): f7-a1-x3
[dashsegments] Total fragments: 21602
[dashsegments] Fragment downloads will be delegated to aria2c
[download] Destination: encrypted.m4a
Exception: [AbstractOptionHandler.cc:69] errorCode=28 We encountered a problem while processing the option '--download-result'.
  -> [OptionHandlerImpl.cc:444] errorCode=1 download-result must be one of the following:'default' 'full' 
Usage:
 --download-result=OPT        This option changes the way "Download Results"
                              is formatted. If OPT is 'default', print GID,
                              status, average download speed and path/URI. If
                              multiple files are involved, path/URI of first
                              requested file is printed and remaining ones are
                              omitted.
                              If OPT is 'full', print GID, status, average
                              download speed, percentage of progress and
                              path/URI. The percentage of progress and
                              path/URI are printed for each requested file in
                              each row.

                              Possible Values: default, full
                              Default: default
                              Tags: #advanced

[aria2c] Got error. Retrying fragments (attempt 1 of 10)...
Exception: [AbstractOptionHandler.cc:69] errorCode=28 We encountered a problem while processing the option '--download-result'.
  -> [OptionHandlerImpl.cc:444] errorCode=1 download-result must be one of the following:'default' 'full' 
Usage:
 --download-result=OPT        This option changes the way "Download Results"
                              is formatted. If OPT is 'default', print GID,
                              status, average download speed and path/URI. If
                              multiple files are involved, path/URI of first
                              requested file is printed and remaining ones are
                              omitted.
                              If OPT is 'full', print GID, status, average
                              download speed, percentage of progress and
                              path/URI. The percentage of progress and
                              path/URI are printed for each requested file in
                              each row.

                              Possible Values: default, full
                              Default: default
                              Tags: #advanced

[aria2c] Got error. Retrying fragments (attempt 2 of 10)...
Exception: [AbstractOptionHandler.cc:69] errorCode=28 We encountered a problem while processing the option '--download-result'.
  -> [OptionHandlerImpl.cc:444] errorCode=1 download-result must be one of the following:'default' 'full' 
Usage:
 --download-result=OPT        This option changes the way "Download Results"
                              is formatted. If OPT is 'default', print GID,
                              status, average download speed and path/URI. If
                              multiple files are involved, path/URI of first
                              requested file is printed and remaining ones are
                              omitted.
                              If OPT is 'full', print GID, status, average
                              download speed, percentage of progress and
                              path/URI. The percentage of progress and
                              path/URI are printed for each requested file in
                              each row.

                              Possible Values: default, full
                              Default: default
                              Tags: #advanced

[aria2c] Got error. Retrying fragments (attempt 3 of 10)...
Exception: [AbstractOptionHandler.cc:69] errorCode=28 We encountered a problem while processing the option '--download-result'.
  -> [OptionHandlerImpl.cc:444] errorCode=1 download-result must be one of the following:'default' 'full' 
Usage:
 --download-result=OPT        This option changes the way "Download Results"
                              is formatted. If OPT is 'default', print GID,
                              status, average download speed and path/URI. If
                              multiple files are involved, path/URI of first
                              requested file is printed and remaining ones are
                              omitted.
                              If OPT is 'full', print GID, status, average
                              download speed, percentage of progress and
                              path/URI. The percentage of progress and
                              path/URI are printed for each requested file in
                              each row.

                              Possible Values: default, full
                              Default: default
                              Tags: #advanced

[aria2c] Got error. Retrying fragments (attempt 4 of 10)...
Exception: [AbstractOptionHandler.cc:69] errorCode=28 We encountered a problem while processing the option '--download-result'.
  -> [OptionHandlerImpl.cc:444] errorCode=1 download-result must be one of the following:'default' 'full' 
Usage:
 --download-result=OPT        This option changes the way "Download Results"
                              is formatted. If OPT is 'default', print GID,
                              status, average download speed and path/URI. If
                              multiple files are involved, path/URI of first
                              requested file is printed and remaining ones are
                              omitted.
                              If OPT is 'full', print GID, status, average
                              download speed, percentage of progress and
                              path/URI. The percentage of progress and
                              path/URI are printed for each requested file in
                              each row.

                              Possible Values: default, full
                              Default: default
                              Tags: #advanced

[aria2c] Got error. Retrying fragments (attempt 5 of 10)...
Exception: [AbstractOptionHandler.cc:69] errorCode=28 We encountered a problem while processing the option '--download-result'.
  -> [OptionHandlerImpl.cc:444] errorCode=1 download-result must be one of the following:'default' 'full' 
Usage:
 --download-result=OPT        This option changes the way "Download Results"
                              is formatted. If OPT is 'default', print GID,
                              status, average download speed and path/URI. If
                              multiple files are involved, path/URI of first
                              requested file is printed and remaining ones are
                              omitted.
                              If OPT is 'full', print GID, status, average
                              download speed, percentage of progress and
                              path/URI. The percentage of progress and
                              path/URI are printed for each requested file in
                              each row.

                              Possible Values: default, full
                              Default: default
                              Tags: #advanced

[aria2c] Got error. Retrying fragments (attempt 6 of 10)...
Exception: [AbstractOptionHandler.cc:69] errorCode=28 We encountered a problem while processing the option '--download-result'.
  -> [OptionHandlerImpl.cc:444] errorCode=1 download-result must be one of the following:'default' 'full' 
Usage:
 --download-result=OPT        This option changes the way "Download Results"
                              is formatted. If OPT is 'default', print GID,
                              status, average download speed and path/URI. If
                              multiple files are involved, path/URI of first
                              requested file is printed and remaining ones are
                              omitted.
                              If OPT is 'full', print GID, status, average
                              download speed, percentage of progress and
                              path/URI. The percentage of progress and
                              path/URI are printed for each requested file in
                              each row.

                              Possible Values: default, full
                              Default: default
                              Tags: #advanced

[aria2c] Got error. Retrying fragments (attempt 7 of 10)...
Exception: [AbstractOptionHandler.cc:69] errorCode=28 We encountered a problem while processing the option '--download-result'.
  -> [OptionHandlerImpl.cc:444] errorCode=1 download-result must be one of the following:'default' 'full' 
Usage:
 --download-result=OPT        This option changes the way "Download Results"
                              is formatted. If OPT is 'default', print GID,
                              status, average download speed and path/URI. If
                              multiple files are involved, path/URI of first
                              requested file is printed and remaining ones are
                              omitted.
                              If OPT is 'full', print GID, status, average
                              download speed, percentage of progress and
                              path/URI. The percentage of progress and
                              path/URI are printed for each requested file in
                              each row.

                              Possible Values: default, full
                              Default: default
                              Tags: #advanced

[aria2c] Got error. Retrying fragments (attempt 8 of 10)...
Exception: [AbstractOptionHandler.cc:69] errorCode=28 We encountered a problem while processing the option '--download-result'.
  -> [OptionHandlerImpl.cc:444] errorCode=1 download-result must be one of the following:'default' 'full' 
Usage:
 --download-result=OPT        This option changes the way "Download Results"
                              is formatted. If OPT is 'default', print GID,
                              status, average download speed and path/URI. If
                              multiple files are involved, path/URI of first
                              requested file is printed and remaining ones are
                              omitted.
                              If OPT is 'full', print GID, status, average
                              download speed, percentage of progress and
                              path/URI. The percentage of progress and
                              path/URI are printed for each requested file in
                              each row.

                              Possible Values: default, full
                              Default: default
                              Tags: #advanced

[aria2c] Got error. Retrying fragments (attempt 9 of 10)...
Exception: [AbstractOptionHandler.cc:69] errorCode=28 We encountered a problem while processing the option '--download-result'.
  -> [OptionHandlerImpl.cc:444] errorCode=1 download-result must be one of the following:'default' 'full' 
Usage:
 --download-result=OPT        This option changes the way "Download Results"
                              is formatted. If OPT is 'default', print GID,
                              status, average download speed and path/URI. If
                              multiple files are involved, path/URI of first
                              requested file is printed and remaining ones are
                              omitted.
                              If OPT is 'full', print GID, status, average
                              download speed, percentage of progress and
                              path/URI. The percentage of progress and
                              path/URI are printed for each requested file in
                              each row.

                              Possible Values: default, full
                              Default: default
                              Tags: #advanced

[aria2c] Got error. Retrying fragments (attempt 10 of 10)...
Exception: [AbstractOptionHandler.cc:69] errorCode=28 We encountered a problem while processing the option '--download-result'.
  -> [OptionHandlerImpl.cc:444] errorCode=1 download-result must be one of the following:'default' 'full' 
Usage:
 --download-result=OPT        This option changes the way "Download Results"
                              is formatted. If OPT is 'default', print GID,
                              status, average download speed and path/URI. If
                              multiple files are involved, path/URI of first
                              requested file is printed and remaining ones are
                              omitted.
                              If OPT is 'full', print GID, status, average
                              download speed, percentage of progress and
                              path/URI. The percentage of progress and
                              path/URI are printed for each requested file in
                              each row.

                              Possible Values: default, full
                              Default: default
                              Tags: #advanced

ERROR: Unable to open fragment 0


ERROR: aria2c exited with code -1
`

**Comment by AndreVuillemot160** [comment]
Next time, put your stuff on some pastebin bruh.
Also, did you modify python script it is self? It's prob still looks for binaries of these programs lol

**Comment by Zachary24** [comment]
> Next time, put your stuff on some pastebin bruh.
> Also, did you modify python script it is self? It's prob still looks for binaries of these programs lol

sorry lol, yeah after installing everything I went in and changed the subprocess calls to fit.

**Comment by Palyer321** [comment]
@Zachary24  Hi, Can you please provide me a detailed explanation on how you installed bento4 properly...Because in my case the script doesn't seems to recognize the mp4decrypt command...Please can you help!
