### ISSUE TITLE
Multi-part Episode Peacock

### ISSUE THREAD

**Issue by RedRaptor10** [parnexcodes/widevine-L3-WEB-DL-Script#30]
For episodes that are split into two parts on Peacock, I'm only able to get the 2nd part of the video (I'm trying this on a cartoon with multiple parts and has an ad-break in between). I assume it's not an issue with the script, but the extension not being able to grab mpd for the 1st part. I also tried manually getting the mpd url from Dev Tools->Network and adding it to the keys.json file but it still only gives me the 2nd part.

**Comment by parnexcodes** [comment]
use method-2 with correct mpd.

**Comment by RedRaptor10** [comment]
Not sure what I'm doing wrong. I tried method 2, it downloaded keys.txt file but the extension wasn't able to find an mpd url. I am using [this](https://github.com/parnexcodes/widevine-l3-guesser-modified) extension for method 2. The show I'm trying it on is "Sitting Ducks", perhaps you can try and see if you can get it to work?

Just to reiterate, the problem seems to be actually finding the mpd url for the 1st half of the episode. The extensions I tried were unsuccessful in that. The best I was able to do was getting the mpd url for the 2nd half.

If not possible then I guess that's fine... I was actually able to find the same show on therokuchannel, which worked with method 1, however it's missing two episodes and is in lower resolution.
