### ISSUE TITLE
Probably Redundant.. Any Workarounds For Grabbing Keys on Linux? 

### ISSUE THREAD

**Issue by ohmybahgosh** [parnexcodes/widevine-L3-WEB-DL-Script#31]
Currently have to use a Microsoft VPS via RDP to grab keys, as I run Linux on my other servers..

Unless something changed, I was under the impression that widevine-l3-guesser only works on windows chrome/firefox/brave..

Are there any workarounds that anyone has found to grab these keys strictly on Linux?  The only thing I have left to try is doing a shitty wine install via chrome_installer.exe, but I'm not holding my breath lol.

Maybe ssh in to the Windows VPS and launch headless chrome.. But, then I'm in the blind to truly verify the content that's loaded, other than sourcecode/xhr requests..

Ideas?

**Comment by parnexcodes** [comment]
I don't think this extension works on linux.
