### ISSUE TITLE
Downloading 2 or more audio in one command

### ISSUE THREAD

**Issue by KaIZeR99-code** [parnexcodes/widevine-L3-WEB-DL-Script#35]
If the video have many languages, how can I download all audio in one command?
I mean can I download many audio when using -id?

**Comment by parnexcodes** [comment]
as much as you want , edit the code according to your needs.

**Comment by KaIZeR99-code** [comment]
ok got it.... thanks.... Already ripped all audio

**Comment by NiKoCZ89** [comment]
> 
> 
> ok got it.... thanks.... I've changed the script and ripped all audio without errors ^_^

can u share?
