### ISSUE TITLE
requested format error

### ISSUE THREAD

**Issue by basava66** [parnexcodes/widevine-L3-WEB-DL-Script#37]
I'm getting error "I'm getting error "ERROR: Requested format is not available" thanks.

**Comment by Essam3152** [comment]
You get this error message because you wrote the wrong id for the video or the audio as in this screenshot.

<img width="388" alt="1515" src="https://user-images.githubusercontent.com/87686356/131245778-b6349147-465b-4f5e-89f0-4fb96cf7153e.png">

**Comment by basava66** [comment]
website : jiocinema 

WARNING: --downloader-args given without specifying name. The arguments will be
given to all external downloaders
[generic] c36ec1408d2611e9951b015ca3b4e167_HD_WEBDESKTOP_A: Requesting header
ERROR: Requested format is not available
WARNING: --downloader-args given without specifying name. The arguments will be
given to all external downloaders
[generic] c36ec1408d2611e9951b015ca3b4e167_HD_WEBDESKTOP_A: Requesting header
ERROR: Requested format is not available

Decrypting .....
ERROR: cannot open input file (encrypted.m4a) -4
ERROR: cannot open input file (encrypted.mp4) -4
Merging .....
mkvmerge v57.0.0 ('Till The End') 64-bit
Error: The file 'decrypted.mp4' could not be opened for reading: open file error
.

All Done .....

Do you want to delete the Encrypted Files : Press 1 for yes , 2 for no
Enter Response :

keys.json file - https://www119.zippyshare.com/v/puBVEtUJ/file.html
thanks.

**Comment by Essam3152** [comment]
I do not know how to modify the script or the link so you would be able to download the video and the audio yet, but from the mpd file the links for downloading the audio and the video and the correct keys are

audio

612684fb0ef004c19f9cf80a6337a589

https://jiovod.wdrm.cdn.jio.com/content/entry/wvdata/20/4/c36ec1408d2611e9951b015ca3b4e167_8192_a.mp4

video

7415d3332100107c654dcef43894a594

https://jiovod.wdrm.cdn.jio.com/content/entry/wvdata/20/4/c36ec1408d2611e9951b015ca3b4e167_896_v.mp4

the video's key from the keys.json file will only decrypt the video up to 896×384.

To find the links download the mpd file with IDM

https://jiovod.wdrm.cdn.jio.com/content/entry/wvdata/20/4/c36ec1408d2611e9951b015ca3b4e167_HD_WEBDESKTOP_A.mpd?jct=wjPzp6X3c7U5hr-4V7xxOA&pxe=1630255207&st=0454a386822f7712ec07d421ad1d8481

then open the file with Notepad++ and search for default_KID and compare the value of the kid to know which key is for the audio and which key is for the video, and how to get the links of the video and the audio.

**Comment by Essam3152** [comment]
Try using the extension from this branch, and see if you could get keys that can decrypt higher resolution. 

https://codeload.github.com/Satsuoni/widevine-l3-guesser/zip/refs/heads/master

**Comment by basava66** [comment]
thanks I can able to decrypt the video and audio also thank you for bat files.

**Comment by Sentivet** [comment]
> thanks I can able to decrypt the video and audio also thank you for bat files.

Do you get keys for hd videos in jiocinema.com? If yes then which widevine decryptor you used?

**Comment by jiomvk** [comment]
> thanks I can able to decrypt the video and audio also thank you for bat files.

@  
Author
basava66, yes for me as well not getting the keys, can you post which one you are using for decrypt keys

**Comment by basava66** [comment]
> > thanks I can able to decrypt the video and audio also thank you for bat files.
> 
> Do you get keys for hd videos in jiocinema.com? If yes then which widevine decryptor you used?

no hd format. Using this one https://github.com/Satsuoni/widevine-l3-guesser only decrypt 

here is the sample medianinfo 

General
Complete name                            :C:\Widevine\Downloads\decrypt\Jamun.mp4
Format                                   : MPEG-4
Format profile                           : Base Media
Codec ID                                 : isom (isom/iso2/avc1/mp41)
File size                                : 1.10 GiB
Duration                                 : 1 h 32 min
Overall bit rate                         : 1 734 kb/s
Writing application                      : Lavf58.76.100

Video
ID                                       : 1
Format                                   : AVC
Format/Info                              : Advanced Video Codec
Format profile                           : Main@L3
Format settings                          : CABAC / 2 Ref Frames
Format settings, CABAC                   : Yes
Format settings, Reference frames        : 2 frames
Codec ID                                 : avc1
Codec ID/Info                            : Advanced Video Coding
Duration                                 : 1 h 32 min
Bit rate                                 : 1 600 kb/s
Width                                    : 864 pixels
Height                                   : 480 pixels
Display aspect ratio                     : 16:9
Frame rate mode                          : Constant
Frame rate                               : 25.000 FPS
Color space                              : YUV
Chroma subsampling                       : 4:2:0
Bit depth                                : 8 bits
Scan type                                : Progressive
Bits/(Pixel*Frame)                       : 0.154
Stream size                              : 1.01 GiB (92%)
Writing library                          : x264 core 138
Encoding settings                        : cabac=1 / ref=1 / deblock=1:0:0 / analyse=0x1:0x111 / me=hex / subme=7 / psy=1 / psy_rd=1.00:0.00 / mixed_ref=0 / me_range=16 / chroma_me=1 / trellis=1 / 8x8dct=0 / cqm=0 / deadzone=21,11 / fast_pskip=1 / chroma_qp_offset=-2 / threads=6 / lookahead_threads=1 / sliced_threads=0 / nr=0 / decimate=1 / interlaced=0 / bluray_compat=0 / constrained_intra=0 / bframes=1 / b_pyramid=0 / b_adapt=2 / b_bias=0 / direct=1 / weightb=1 / open_gop=0 / weightp=2 / keyint=50 / keyint_min=5 / scenecut=0 / intra_refresh=0 / rc_lookahead=50 / rc=abr / mbtree=1 / bitrate=1600 / ratetol=1.0 / qcomp=0.60 / qpmin=0 / qpmax=69 / qpstep=4 / vbv_maxrate=2240 / vbv_bufsize=3200 / nal_hrd=none / filler=0 / ip_ratio=1.40 / aq=1:1.00
Language                                 : English
Codec configuration box                  : avcC

Audio
ID                                       : 2
Format                                   : AAC LC
Format/Info                              : Advanced Audio Codec Low Complexity
Codec ID                                 : mp4a-40-2
Duration                                 : 1 h 32 min
Bit rate mode                            : Constant
Bit rate                                 : 128 kb/s
Channel(s)                               : 2 channels
Channel layout                           : L R
Sampling rate                            : 48.0 kHz
Frame rate                               : 46.875 FPS (1024 SPF)
Compression mode                         : Lossy
Stream size                              : 82.6 MiB (7%)
Language                                 : English
Default                                  : Yes
Alternate group                          : 1

**Comment by jiomvk** [comment]
> > > thanks I can able to decrypt the video and audio also thank you for bat files.
> > 
> > 
> > Do you get keys for hd videos in jiocinema.com? If yes then which widevine decryptor you used?
> 
> no hd format. Using this one https://github.com/Satsuoni/widevine-l3-guesser only decrypt
> 
> here is the sample medianinfo
> 
> General
> Complete name :C:\Widevine\Downloads\decrypt\Jamun.mp4
> Format : MPEG-4
> Format profile : Base Media
> Codec ID : isom (isom/iso2/avc1/mp41)
> File size : 1.10 GiB
> Duration : 1 h 32 min
> Overall bit rate : 1 734 kb/s
> Writing application : Lavf58.76.100
> 
> Video
> ID : 1
> Format : AVC
> Format/Info : Advanced Video Codec
> Format profile : Main@L3
> Format settings : CABAC / 2 Ref Frames
> Format settings, CABAC : Yes
> Format settings, Reference frames : 2 frames
> Codec ID : avc1
> Codec ID/Info : Advanced Video Coding
> Duration : 1 h 32 min
> Bit rate : 1 600 kb/s
> Width : 864 pixels
> Height : 480 pixels
> Display aspect ratio : 16:9
> Frame rate mode : Constant
> Frame rate : 25.000 FPS
> Color space : YUV
> Chroma subsampling : 4:2:0
> Bit depth : 8 bits
> Scan type : Progressive
> Bits/(Pixel*Frame) : 0.154
> Stream size : 1.01 GiB (92%)
> Writing library : x264 core 138
> Encoding settings : cabac=1 / ref=1 / deblock=1:0:0 / analyse=0x1:0x111 / me=hex / subme=7 / psy=1 / psy_rd=1.00:0.00 / mixed_ref=0 / me_range=16 / chroma_me=1 / trellis=1 / 8x8dct=0 / cqm=0 / deadzone=21,11 / fast_pskip=1 / chroma_qp_offset=-2 / threads=6 / lookahead_threads=1 / sliced_threads=0 / nr=0 / decimate=1 / interlaced=0 / bluray_compat=0 / constrained_intra=0 / bframes=1 / b_pyramid=0 / b_adapt=2 / b_bias=0 / direct=1 / weightb=1 / open_gop=0 / weightp=2 / keyint=50 / keyint_min=5 / scenecut=0 / intra_refresh=0 / rc_lookahead=50 / rc=abr / mbtree=1 / bitrate=1600 / ratetol=1.0 / qcomp=0.60 / qpmin=0 / qpmax=69 / qpstep=4 / vbv_maxrate=2240 / vbv_bufsize=3200 / nal_hrd=none / filler=0 / ip_ratio=1.40 / aq=1:1.00
> Language : English
> Codec configuration box : avcC
> 
> Audio
> ID : 2
> Format : AAC LC
> Format/Info : Advanced Audio Codec Low Complexity
> Codec ID : mp4a-40-2
> Duration : 1 h 32 min
> Bit rate mode : Constant
> Bit rate : 128 kb/s
> Channel(s) : 2 channels
> Channel layout : L R
> Sampling rate : 48.0 kHz
> Frame rate : 46.875 FPS (1024 SPF)
> Compression mode : Lossy
> Stream size : 82.6 MiB (7%)
> Language : English
> Default : Yes
> Alternate group : 1
> 
> edit : accidentally closed the thread.

@basava66 :  Thanks a lot, now able to find the keys, as you mentioned its only sd. 

@Essam3152: Thank you as well for providing the right info and your method worked for downloading the mpd and decrypting the SD content, but unfortunately not able to find the KID : key for HD content, even though we can download the HD format mp4 unable to decrypt due to lack of correct key.

**Comment by Essam3152** [comment]
@jiomvk I think to download and decrypt the video in HD from this site you most likely will need a paid script (and every site that does not provide the video in HD or 4K on Windows but provide them in HD or 4K on the android devices that support widevine l1), which I have no idea if this script is even exists or from where you could get it. I just know that you could download and decrypt the video from Netflix and Amazon in 4K using paid scripts, but I never used any of them by myself because they cost a lot of money and I have no need for them.

**Comment by basava66** [comment]
@jiomvk  for content wise you can try Airtelxstream or vi movies and erosnow three of them are mostly cover  jiocinema content.

**Comment by ank003** [comment]
>  all credit goes to @Essam3152 and @jiomvk for content wise you can try Airtelxstream or vi movies and erosnow three of them are mostly cover  jiocinema content.

Hey buddy i want to try form Airtelxstream but I'm getting 403 forbidden error continuously .... Like the main link is 

https://www.airtelxstream.in/movies/jiilka/NAMMAFLIX_MOVIE_6135c2da4bdb2711dbc3b40a 

Mpd link 
https://nammaflix-streams.streamready.in/NAMMAFLIX/FEATUREFILM/6135c2da4bdb2711dbc3b40a/dash/manifest.mpd?Policy=eyJTdGF0ZW1lbnQiOiBbeyJSZXNvdXJjZSI6Imh0dHBzOi8vbmFtbWFmbGl4LXN0cmVhbXMuc3RyZWFtcmVhZHkuaW4vTkFNTUFGTElYL0ZFQVRVUkVGSUxNLzYxMzVjMmRhNGJkYjI3MTFkYmMzYjQwYS9kYXNoLyoiLCJDb25kaXRpb24iOnsiRGF0ZUxlc3NUaGFuIjp7IkFXUzpFcG9jaFRpbWUiOjE2MzMyNTE4MjB9fX1dfQ__&Key-Pair-Id=APKAIWHAQM7JDJRYIKDA&Signature=Ut1nCPrx8gZygiMXHGZzIwg1TNCrqNHj5o9o6O8r4hdQoptOVE2XDDVnQN8THJDsLcrR1Z1YjzJrc3mQ9qy-r2zkPJEjmTCkcGkQi1IcAOI7fCzFkiipiwuAQiojKjn1p9yTo641urmU9fAGZSP018IIAecoN~n7YsUKcoRIUipxLOv1fGfhWvH7B4b5yunPQav9OsHu8XhmErlPEWXZUSk7MihC8FcBzihwXuu68458QJyGPVkr1or1ApENw76qFjevg0yNiIlLxjbawjAwRusZoWxyzeAqbadmGs7F4tqIFDh8-xj085iWs6p2efM62TvYlKdRHJlhJsSwR7EaOw__&spid=NAMMAFLIX-XSTREAM&request-id=F60BE12A071D470892A82135E5305FD6&uid=0cvABY9UGpXoKeM3i0 

And i have also got the keys ... When i try with this script it says .... 

![IMG_20211003_125954_328.jpg](https://user-images.githubusercontent.com/89583050/135744407-4ac0309e-3cc5-49c9-b372-3a82140a20b4.jpg) 

Please help me
