### ISSUE TITLE
Can this script apply for fubotv site

### ISSUE THREAD

**Issue by doxuyenxo** [parnexcodes/widevine-L3-WEB-DL-Script#4]
Thank you so much for your sharing script.
I try with fuboTv stream, it's can download and decrypt successful. But still can't decrypt.
I did wrong or this script can't download fuboTv video? 
Thank again!

**Comment by parnexcodes** [comment]
Must be key issue , i have updated the method.
Check readme.

**Comment by doxuyenxo** [comment]
Awesome. You save my day. Thank you so much, bro! :D
