### ISSUE TITLE
Exception: [AbstractCommand.cc:351] errorCode=22

### ISSUE THREAD

**Issue by Sentivet** [parnexcodes/widevine-L3-WEB-DL-Script#40]
CUID#7 - Download aborted. URI=https://a129avoddashs3ww-a.akamaihd.net/d/2$d64r_SMqqDbYg34zwYEUrbx6y5g~/1@43cf6c9b085364d3f2b5bf4a87198688/ondemand/ww_bom/a1ec/073e/ca24/40a4-b323-65da5c42fad3/ww_bom/a1ec/073e/ca24/40a4-b323-65da5c42fad3/46c4562a-78fa-4d8a-932f-78d96884dfec_audio_11.mp4
Exception: [AbstractCommand.cc:351] errorCode=22 URI=https://a129avoddashs3ww-a.akamaihd.net/d/2$d64r_SMqqDbYg34zwYEUrbx6y5g~/1@43cf6c9b085364d3f2b5bf4a87198688/ondemand/ww_bom/a1ec/073e/ca24/40a4-b323-65da5c42fad3/ww_bom/a1ec/073e/ca24/40a4-b323-65da5c42fad3/46c4562a-78fa-4d8a-932f-78d96884dfec_audio_11.mp4
  -> [HttpSkipResponseCommand.cc:240] errorCode=22 The response status is not successful. status=403

How to overcome this error?

**Comment by Essam3152** [comment]
Could you post the link of the video?

**Comment by Sentivet** [comment]
https://www.primevideo.com/detail/0G9H0FL8U1LVEOA7YB8N7G2TMN/ref=atv_hm_hom_c_7d0kid_2_1 This is the link of the video. I tried with different videos. I am using Keys.json file for downloading. But getting this error while downloading. What is the problem?

**Comment by Essam3152** [comment]
This is the mpd that worked.

https://m-2704s3.ll.dash.row.aiv-cdn.net/d/2$WRKNrtcSNaLEAcVIO5WygYgioZg~/ww_bom/a1ec/073e/ca24/40a4-b323-65da5c42fad3/46c4562a-78fa-4d8a-932f-78d96884dfec_corrected.mpd?amznDtid=AOAGZA014O5RE&encoding=segmentBase

audio key

KID= daf3560b5f884b219ed56c9f7c345080 Key: 1aaa87eb3442c99b4d6fd6f2ff285c4c 

video key

KID= 1e5b493f4ec94e8fb373ea8327b96045 Key: 738804a942cec453c6b27b56e5735c81 

audio link

https://m-2704s3.ll.dash.row.aiv-cdn.net/d/2$WRKNrtcSNaLEAcVIO5WygYgioZg~/ww_bom/a1ec/073e/ca24/40a4-b323-65da5c42fad3/46c4562a-78fa-4d8a-932f-78d96884dfec_audio_11.mp4

video link

https://m-2704s3.ll.dash.row.aiv-cdn.net/d/2$WRKNrtcSNaLEAcVIO5WygYgioZg~/ww_bom/a1ec/073e/ca24/40a4-b323-65da5c42fad3/46c4562a-78fa-4d8a-932f-78d96884dfec_video_12.mp4

keys.json

[keys.zip](https://github.com/parnexcodes/widevine-L3-WEB-DL-Script/files/7077853/keys.zip)

**Comment by Sentivet** [comment]
Thanks its working. But how you got these keys.json file? I am using this one https://github.com/parnexcodes/widevine-l3-guesser-modified

**Comment by Essam3152** [comment]
I'm using the same extension on Google Chrome, try using this method to find the correct mpd.

https://github.com/Satsuoni/widevine-l3-guesser/issues/1#issuecomment-903831304

**Comment by parnexcodes** [comment]
> 
> 
> Thanks its working. But how you got these keys.json file? Which extension you are using? I am using this one https://github.com/parnexcodes/widevine-l3-guesser-modified and I am getting this file.
> [keys.zip](https://github.com/parnexcodes/widevine-L3-WEB-DL-Script/files/7077932/keys.zip)
> This mpd file getting the above error.

I suggest using https://github.com/parnexcodes/widevine-L3-WEB-DL-Script/tree/method-2
because the main branch code isn't universal to every site. You'll need to modify some code for it to work for every other site.
