### ISSUE TITLE
Decrypt .mp4 file downloaded using n_m3u8

### ISSUE THREAD

**Issue by oknchm** [parnexcodes/widevine-L3-WEB-DL-Script#42]
I tested this script with .mpd files and it works great, but the videos I want are only available in .m3u8 so I used the n_m3u8 program like mentioned in the README. It downloaded an .mp4 file but it's still encrypted and won't play. Using the Widevine Guesser extension found keys on the website (of the m3u8 file). I was wondering if it's possible to decrypt the .mp4 file I have using this script with those keys? Thank you!

**Comment by Essam3152** [comment]
You could use mp4info.exe from this comment to know the kid's value of the files and by comparing them with the kid's value you got by using Widevine Guesser you will know which key will decrypt the audio and which key will decrypt the video.

https://github.com/Satsuoni/widevine-l3-guesser/issues/1#issuecomment-903831304

Then use mp4decrypt.exe from this comment to decrypt the files.

https://github.com/parnexcodes/widevine-L3-WEB-DL-Script/issues/37#issuecomment-907805191

It will help if you could post the link of the m3u8 link, and the link of video in the site.

**Comment by Sentivet** [comment]
U can use xstream cli downloader to download m3u8 files. It supports decryting also

**Comment by arbarbosa1979** [comment]
@oknchm You can use mp4decrypt to decrypt the video, you just need to provide the kid and the key, and indicate the complete path of the encrypted video. In my example it has three KID and KEY because the site provides 3, so if your site only provides one KID and KEY, then delete the other --keys and leave only one.

`mp4decrypt --show-progress --key KID1:KEY1 --key KID2:KEY2 --key KID3:KEY3 enc.mp4 dec.mp4`

**Comment by oknchm** [comment]
Thank you all for the responses! I'll try them soon.

**Comment by troufiniou** [comment]
> @oknchm You can use mp4decrypt to decrypt the video, you just need to provide the kid and the key, and indicate the complete path of the encrypted video. In my example it has three KID and KEY because the site provides 3, so if your site only provides one KID and KEY, then delete the other --keys and leave only one.
> 
> `mp4decrypt --show-progress --key KID1:KEY1 --key KID2:KEY2 --key KID3:KEY3 enc.mp4 dec.mp4`

I've the two KID and KEY but looks like he can't decode. Is it possible that the extension give bad key ?

**Comment by jtrahan** [comment]
@troufiniou there is a mp4decrypt_new.exe in the binaries folder. Give that one a try.
