### ISSUE TITLE
download video from amazon with all audio comes with it 

### ISSUE THREAD

**Issue by hossam1111199** [parnexcodes/widevine-L3-WEB-DL-Script#46]
how to download multiple audio from amazon at once with video

**Comment by Essam3152** [comment]
You could modify the script to download as many languages as you need, but you will edit the script for each video if you want to download all the audio languages that are available, I modified the script to download two audio languages, the default audio language will be English and second audio language will be Arabic, if you want to change the default audio language from English to any other language replace "eng" in 

`'--language', '0:eng', '--default-track', '0:yes', '--compression' ,'0:none', 'decrypted.m4a'` 

with the code of the language you want to be the default language, and to change the second language code replace "ara", to start the script run Download.bat then enter the ID of the video which will be something like video=15000000 and press enter, then enter the ID of the English audio which will something like audio_en-US_3=192000 and press enter, then enter the ID of the Arabic audio which will be something like audio_ar-EG_3=128000 and press enter, and the script will download the files and decrypt and merge them. 

[widevine-L3-WEB-DL-Script-2Audio.zip](https://github.com/parnexcodes/widevine-L3-WEB-DL-Script/files/7117943/widevine-L3-WEB-DL-Script-2Audio.zip)

The script has keys.json with it for a cartoon, the size of the file is not big, you could test the modified script with it, I'm not sure if there is an easier way for modifying this script to download multiples audio files, this is what I did:

after
`    audio_id = input("Enter Audio ID : ")`

I added for the second audio

`    audio2_id = input("Enter Audio ID : ")`

then added

`    subprocess.run([youtubedlexe, '-k', '--allow-unplayable-formats', '--no-check-certificate', '-f', audio2_id, '--fixup', 'never', json_mpd_url, '-o', 'encrypted2.m4a', '--external-downloader', aria2cexe, '--external-downloader-args', '-x 16 -s 16 -k 1M'])`

encrypted2.m4a is the second encrypted audio

then added

`    subprocess.run([youtubedlexe, '-k', '--allow-unplayable-formats', '--no-check-certificate', '-f', 'ba', '--fixup', 'never', json_mpd_url, '-o', 'encrypted2.m4a', '--external-downloader', aria2cexe, '--external-downloader-args', '-x 16 -s 16 -k 1M'])`

and after that added

`subprocess.run(f'{mp4decryptexe} --show-progress {keys} encrypted2.m4a decrypted2.m4a', shell=True)`

and changed the script from

`    subprocess.run([mkvmergeexe, '--ui-language' ,'en', '--output', output +'.mkv', '--language', '0:eng', '--default-track', '0:yes', '--compression', '0:none', 'decrypted.mp4', '--language', '0:eng', '--default-track', '0:yes', '--compression' ,'0:none', 'decrypted.m4a','--language', '0:eng','--track-order', '0:0,1:0,2:0,3:0,4:0', 'en.srt'])`

to

`    subprocess.run([mkvmergeexe, '--ui-language' ,'en', '--output', output +'.mkv', '--language', '0:eng', '--default-track', '0:yes', '--compression', '0:none', 'decrypted.mp4', '--language', '0:eng', '--default-track', '0:yes', '--compression' ,'0:none', 'decrypted.m4a', '--language', '0:ara', '--default-track', '0:no', '--compression' ,'0:none', 'decrypted2.m4a', '--language', '0:eng','--track-order', '0:0,1:0,2:0,3:0,4:0', 'en.srt'])`

and from

`    subprocess.run([mkvmergeexe, '--ui-language' ,'en', '--output', output +'.mkv', '--language', '0:eng', '--default-track', '0:yes', '--compression', '0:none', 'decrypted.mp4', '--language', '0:eng', '--default-track', '0:yes', '--compression' ,'0:none', 'decrypted.m4a','--language', '0:eng','--track-order', '0:0,1:0,2:0,3:0,4:0'])`

to

`    subprocess.run([mkvmergeexe, '--ui-language' ,'en', '--output', output +'.mkv', '--language', '0:eng', '--default-track', '0:yes', '--compression', '0:none', 'decrypted.mp4', '--language', '0:eng', '--default-track', '0:yes', '--compression' ,'0:none', 'decrypted.m4a', '--language', '0:ara', '--default-track', '0:no', '--compression' ,'0:none', 'decrypted2.m4a', '--language', '0:eng','--track-order', '0:0,1:0,2:0,3:0,4:0'])`

the last thing is changing the script from

`    os.remove("encrypted.m4a")
    os.remove("encrypted.mp4")
    os.remove("decrypted.m4a")
    os.remove("decrypted.mp4")`

to

`    os.remove("encrypted.m4a")
    os.remove("encrypted2.m4a") 
    os.remove("encrypted.mp4")
    os.remove("decrypted.m4a")
    os.remove("decrypted2.m4a")
    os.remove("decrypted.mp4")`

**Comment by Sentivet** [comment]
@Essam3152 how to contact you personally to clarify some doubts?

**Comment by Essam3152** [comment]
@Sentivet If you have an account in subscene.com post it here and you could send to me a private message.

**Comment by Sentivet** [comment]
@Essam3152 https://subscene.com/u/1394949

**Comment by Essam3152** [comment]
@Sentivet Now delete your two comments.

**Comment by oribe522** [comment]
same for me
