### ISSUE TITLE
amazon videos are not visible

### ISSUE THREAD

**Issue by userxd69** [parnexcodes/widevine-L3-WEB-DL-Script#48]

**Comment by userxd69** [comment]
**after decrypting it not visible checkout this ss**

![photo_2021-09-07_14-43-32](https://user-images.githubusercontent.com/89330562/132318676-d73e90f0-18c3-46a6-bea1-a86cb03b0e54.jpg)

**Comment by Essam3152** [comment]
Post the link of the movie or the episode you used.

**Comment by userxd69** [comment]
> Post the link of the movie or the episode you used, and from which country.

**Interstellar**

https://www.primevideo.com/detail/0I9WWNH0WX2Q545OV1W8O1SFE1/ref=atv_dp_share_cu_r

**JSON File** 
[https://gofile.io/d/LtI5Zb](url)

**Comment by userxd69** [comment]
> Use this copy of the script, it has a working keys.json for the film Interstellar, I downloaded it and tested it and it works fine, just run Download.bat and enter the ID of the video and the ID of the audio.
> 
> [widevine-L3-WEB-DL-Script.zip](https://github.com/parnexcodes/widevine-L3-WEB-DL-Script/files/7120822/widevine-L3-WEB-DL-Script.zip)

Thanks it worked but whats the error might be?
should i use vpn?

**Comment by Essam3152** [comment]
You have two right kids in your keys.json that have two wrong keys with them, the video decrypted with the wrong key. 

right kid, wrong key

`  {
    "kid": "6202e6603e9d4b7681dfb722338dbe4b",
    "hex_key": "0938e0d5f6ff2a4fd27a0def45e9c7b7"
  },
  {
    "kid": "d4656ea4df7f4e89b7942eb4ad4d05d4",
    "hex_key": "1b443e59ffc7317a4e0a8e0259ce24a1"
  },`

right kid, right key

`  {
    "kid": "6202e6603e9d4b7681dfb722338dbe4b",
    "hex_key": "182fea2a9dbc9f75f924a04f3be2b971"
  },
  {
    "kid": "d4656ea4df7f4e89b7942eb4ad4d05d4",
    "hex_key": "dbf1134c27ae7553c63c8ac408425330"
  }`

**Comment by userxd69** [comment]
> You have two right kids in your keys.json that have two wrong keys with them, the video decrypted with the wrong key.
> 
> right kid, wrong key
> 
> ` { "kid": "6202e6603e9d4b7681dfb722338dbe4b", "hex_key": "0938e0d5f6ff2a4fd27a0def45e9c7b7" }, { "kid": "d4656ea4df7f4e89b7942eb4ad4d05d4", "hex_key": "1b443e59ffc7317a4e0a8e0259ce24a1" },`
> 
> right kid, right key
> 
> ` { "kid": "6202e6603e9d4b7681dfb722338dbe4b", "hex_key": "182fea2a9dbc9f75f924a04f3be2b971" }, { "kid": "d4656ea4df7f4e89b7942eb4ad4d05d4", "hex_key": "dbf1134c27ae7553c63c8ac408425330" }`

**so how would i find that both are correct?**

**Comment by userxd69** [comment]
> You have two right kids in your keys.json that have two wrong keys with them, the video decrypted with the wrong key.
> 
> right kid, wrong key
> 
> ` { "kid": "6202e6603e9d4b7681dfb722338dbe4b", "hex_key": "0938e0d5f6ff2a4fd27a0def45e9c7b7" }, { "kid": "d4656ea4df7f4e89b7942eb4ad4d05d4", "hex_key": "1b443e59ffc7317a4e0a8e0259ce24a1" },`
> 
> right kid, right key
> 
> ` { "kid": "6202e6603e9d4b7681dfb722338dbe4b", "hex_key": "182fea2a9dbc9f75f924a04f3be2b971" }, { "kid": "d4656ea4df7f4e89b7942eb4ad4d05d4", "hex_key": "dbf1134c27ae7553c63c8ac408425330" }`

Thank You So Much Bruh****
