### ISSUE TITLE
Why hotstar & Netflix Drm videos are not working

### ISSUE THREAD

**Issue by userxd69** [parnexcodes/widevine-L3-WEB-DL-Script#49]
**Why hotstar Drm videos are not working**

**Comment by Essam3152** [comment]
Netflix does not work with the modified extension https://github.com/parnexcodes/widevine-l3-guesser-modified because it does not use mpd.

**Comment by userxd69** [comment]
> Netflix does not work with the modified extension https://github.com/parnexcodes/widevine-l3-guesser-modified because it does not use mpd.

**okayy so there any other method? and what about hotstar?**

**Comment by Essam3152** [comment]
There is a free method for downloading the video and audio manually from Netflix and decrypt the video but it's not an easy method, Hotstar is not in my country, press F12 then play any movie and search in Network for m3u8 and see if you will get any links.

**Comment by userxd69** [comment]
Hotstar has mpd link but when using windvine it says http error..

**Comment by Essam3152** [comment]
Try this extension instead of the modified one, remove the modified extension first, and see if you will get any keys in the console with this newer original extension.

https://codeload.github.com/Satsuoni/widevine-l3-guesser/zip/refs/heads/master
