### ISSUE TITLE
It works but got Traceback when Enter Response "1"

### ISSUE THREAD

**Issue by vikkstar12** [parnexcodes/widevine-L3-WEB-DL-Script#5]
> Do you want to delete the Encrypted Files : Press 1 for yes , 2 for no
Enter Response : 1
Traceback (most recent call last):
  File "PATH\webdl.py", line 105, in <module>
    os.remove("en.xml")
FileNotFoundError: [WinError 2] The system cannot find the file specified: 'en.xml'

en.xml? what is that?

**Comment by parnexcodes** [comment]
Fixed it new update , you can ignore that error.

**Comment by vikkstar12** [comment]
> Fixed it in new update , you can ignore that error.

well after i update and using the new mod extension, a new traceback again.

> Traceback (most recent call last):
  File "C:\Users\Administrator\Downloads\widevine-L3-WEB-DL-Script-main\webdl.py", line 28, in <module>
    keys += f"--key {config[i]['kid']}:{config[i]['hex_key']} "
KeyError: 'kid'

> During handling of the above exception, another exception occurred:

> Traceback (most recent call last):
  File "C:\Users\Administrator\Downloads\widevine-L3-WEB-DL-Script-main\webdl.py", line 32, in <module>
    keys += f"--key {config[i]['kid']}:{config[i]['hex_key']} "
KeyError: 'kid'

**Comment by parnexcodes** [comment]
> 
> 
> > Fixed it in new update , you can ignore that error.
> 
> well after i update and using the new mod extension, a new traceback again.
> 
> > Traceback (most recent call last):
> > File "C:\Users\Administrator\Downloads\widevine-L3-WEB-DL-Script-main\webdl.py", line 28, in 
> > keys += f"--key {config[i]['kid']}:{config[i]['hex_key']} "
> > KeyError: 'kid'
> 
> > During handling of the above exception, another exception occurred:
> 
> > Traceback (most recent call last):
> > File "C:\Users\Administrator\Downloads\widevine-L3-WEB-DL-Script-main\webdl.py", line 32, in 
> > keys += f"--key {config[i]['kid']}:{config[i]['hex_key']} "
> > KeyError: 'kid'

Update again , sorry for the issue.

**Comment by vikkstar12** [comment]
here https://textbin.net/raw/ssvdpl6vly

**Comment by parnexcodes** [comment]
Change ```for i in range(1, len(config)-1):```

to ```for i in range(1, len(config)-2):```

You can find that value `2` by checking number of mpd_urls after key.
It's a silly error , i will what I can do to avoid this.

**Comment by vikkstar12** [comment]
It work smooth!! Thank you!
