### ISSUE TITLE
Prime Music

### ISSUE THREAD

**Issue by cbesmok** [parnexcodes/widevine-L3-WEB-DL-Script#50]
How to download audio files from prime music ? can able to get the keys but not mpd url thanks in advance.

**Comment by parnexcodes** [comment]
Prime Music or any other music platform doesn't provide mpd afaik.

**Comment by Superhackman** [comment]
There is a way to download music from amazon music or amazon music hd using the application and fiddler and it also shows the KID and shows the file information such as the codec and the quality and a base url for the download, atmos, flac hires or cd quality and mp3 but there is a problem and it is that I do not know how to obtain the url of the license base to generate the decryption key with the NODRM tools uploaded here on github or convert widevine l3 decrypt into an .exe file to capture the key and the kid using any traffic detector library on the network

and by the way, amazon music and amazon music hd use widevine l3 and also if comparing the captured traffic with fiddler and the app either android or windows vs the web player with chrome, both use the same server url and the base url where it is shows the information and the base links for download with their respective codecs and qualities except that the web player is only up to 256kbps mp3

And another thing that I discovered is that the files you download are not fully encrypted, at first it is heard 29 seconds but not later, it may be more or less

**Comment by Superhackman** [comment]
https://music.amazon.com/NA/api/dmls/getDashManifestsV2
`{
  "contentResponseList": [
    {
      "assetQualities": [
        {
          "quality": "HI_RES",
          "rank": 3000
        },
        {
          "quality": "CD",
          "rank": 2000
        },
        {
          "quality": "MP3",
          "rank": 1000
        }
      ],
      "cdnType": "cf-d37b6sgey2y8gt",
      "contentIdentifier": {
        "identifier": "B077H9QTNW",
        "identifierType": "ASIN"
      },
      "contentResponseStatusCode": "SUCCESS",
      "contentResponseStatusMessage": "",
      "manifest": "<?xml version=\"1.0\" encoding=\"UTF-8\" standalone=\"yes\"?>\n<MPD minBufferTime=\"PT2S\" type=\"static\" mediaPresentationDuration=\"PT232.25131225585938S\" profiles=\"urn:mpeg:dash:profile:isoff-on-demand:2011\" xmlns=\"urn:mpeg:dash:schema:mpd:2011\" xmlns:amz-music=\"urn:amazon:music:drm:2019\" xmlns:cenc=\"urn:mpeg:cenc:2013\" xmlns:mspr=\"urn:microsoft:playready\">\n    <Period id=\"0\">\n        <AdaptationSet id=\"1\" contentType=\"audio\" selectionPriority=\"2000\">\n            <ContentProtection schemeIdUri=\"urn:mpeg:dash:mp4protection:2011\" cenc:default_KID=\"e7cae012-8c5e-8514-6356-1dfae3f04b6f\" value=\"cenc\"/>\n            <ContentProtection schemeIdUri=\"urn:uuid:edef8ba9-79d6-4ace-a3c8-27dcd51d21ed\" value=\"AmzMusic-2019\">\n                <cenc:pssh>AAAAs3Bzc2gAAAAA7e+LqXnWSs6jyCfc1R0h7QAAAJMiHGNpZDpmMDByMDJFZVh6em5qNGhLelhaSmxRPT04AFAAWAJqEUtBVEFOQV9DT05URU5UOlVTcloKEH9NK9NhHl8854+ISs12SZUSEOfK4BKMXoUUY1Yd+uPwS28aIDerdLdweSmirTLORZyG2I2WXXI1jdmE0nQOCJBZ1Wi2IhASTqw02e7UpG/lA4pF20JBKCA=</cenc:pssh>\n                <amz-music:groupId>KATANA_CONTENT:US</amz-music:groupId>\n                <amz-music:expires>2020-01-22T00:00:00Z</amz-music:expires>\n                <amz-music:masterKeyId>7F4D2BD3611E5F3CE78F884ACD764995</amz-music:masterKeyId>\n            </ContentProtection>\n            <SupplementalProperty schemeIdUri=\"urn:mpeg:mpegB:cicp:ProgramLoudness\" value=\"-10.0 LUFS\"/>\n            <SupplementalProperty schemeIdUri=\"amz-music:trackType\" value=\"HD\"/>\n            <SupplementalProperty schemeIdUri=\"urn:mpeg:dash:adaptation-set-switching:2016\" value=\"2\"/>\n            <SupplementalProperty schemeIdUri=\"urn:mpeg:mpegB:cicp:AnchorLoudness\" value=\"-7.4 LUFS\"/>\n            <Representation id=\"1\" qualityRanking=\"4\" codecs=\"flac\" audioSamplingRate=\"44100\" bandwidth=\"1033097\" mimeType=\"audio/mp4\">\n                <AudioChannelConfiguration schemeIdUri=\"urn:mpeg:dash:23003:3:audio_channel_configuration:2011\" value=\"2\"/>\n                <SupplementalProperty schemeIdUri=\"amz-music:bitDepth\" value=\"16\"/>\n                <BaseURL>https://d37b6sgey2y8gt.cloudfront.net/1d5482d6-7200000335449908/9c13109a-6231-3004-a10a-f81c488c9868.mp4?r=75e8534e-6083-4a33-9e95-e3c5bf1c9fdd&amp;rs=NA&amp;mt=US</BaseURL>\n                <SegmentList timescale=\"44100\" duration=\"441000\">\n                    <Initialization range=\"0-1055\"/>\n                    <SegmentURL mediaRange=\"1376-1017743\"/>\n                    <SegmentURL mediaRange=\"1017744-2013724\"/>\n                    <SegmentURL mediaRange=\"2013725-3004597\"/>\n                    <SegmentURL mediaRange=\"3004598-4049696\"/>\n                    <SegmentURL mediaRange=\"4049697-5223374\"/>\n                    <SegmentURL mediaRange=\"5223375-6372057\"/>\n                    <SegmentURL mediaRange=\"6372058-7268104\"/>\n                    <SegmentURL mediaRange=\"7268105-8293512\"/>\n                    <SegmentURL mediaRange=\"8293513-9430690\"/>\n                    <SegmentURL mediaRange=\"9430691-10557032\"/>\n                    <SegmentURL mediaRange=\"10557033-11706827\"/>\n                    <SegmentURL mediaRange=\"11706828-12945374\"/>\n                    <SegmentURL mediaRange=\"12945375-14174397\"/>\n                    <SegmentURL mediaRange=\"14174398-15125303\"/>\n                    <SegmentURL mediaRange=\"15125304-16193515\"/>\n                    <SegmentURL mediaRange=\"16193516-17386353\"/>\n                    <SegmentURL mediaRange=\"17386354-18635717\"/>\n                    <SegmentURL mediaRange=\"18635718-19839553\"/>\n                    <SegmentURL mediaRange=\"19839554-21070265\"/>\n                    <SegmentURL mediaRange=\"21070266-22346729\"/>\n                    <SegmentURL mediaRange=\"22346730-23638100\"/>\n                    <SegmentURL mediaRange=\"23638101-24904265\"/>\n                    <SegmentURL mediaRange=\"24904266-25757989\"/>\n                    <SegmentURL mediaRange=\"25757990-25797277\"/>\n                </SegmentList>\n            </Representation>\n            <Representation id=\"2\" qualityRanking=\"0\" codecs=\"flac\" audioSamplingRate=\"44100\" bandwidth=\"1738799\" mimeType=\"audio/mp4\">\n                <AudioChannelConfiguration schemeIdUri=\"urn:mpeg:dash:23003:3:audio_channel_configuration:2011\" value=\"2\"/>\n                <SupplementalProperty schemeIdUri=\"amz-music:bitDepth\" value=\"24\"/>\n                <BaseURL>https://d37b6sgey2y8gt.cloudfront.net/1d5482d6-7200000335449908/fbc46d81-d895-38b2-82bb-dc068c72754f.mp4?r=75e8534e-6083-4a33-9e95-e3c5bf1c9fdd&amp;rs=NA&amp;mt=US</BaseURL>\n                <SegmentList timescale=\"44100\" duration=\"441000\">\n                    <Initialization range=\"0-1055\"/>\n                    <SegmentURL mediaRange=\"1376-1892022\"/>\n                    <SegmentURL mediaRange=\"1892023-3768843\"/>\n                    <SegmentURL mediaRange=\"3768844-5641570\"/>\n                    <SegmentURL mediaRange=\"5641571-7568882\"/>\n                    <SegmentURL mediaRange=\"7568883-9624699\"/>\n                    <SegmentURL mediaRange=\"9624700-11655569\"/>\n                    <SegmentURL mediaRange=\"11655570-13432244\"/>\n                    <SegmentURL mediaRange=\"13432245-15339520\"/>\n                    <SegmentURL mediaRange=\"15339521-17358876\"/>\n                    <SegmentURL mediaRange=\"17358877-19367388\"/>\n                    <SegmentURL mediaRange=\"19367389-21399275\"/>\n                    <SegmentURL mediaRange=\"21399276-23519968\"/>\n                    <SegmentURL mediaRange=\"23519969-25631146\"/>\n                    <SegmentURL mediaRange=\"25631147-27462852\"/>\n                    <SegmentURL mediaRange=\"27462853-29413006\"/>\n                    <SegmentURL mediaRange=\"29413007-31488007\"/>\n                    <SegmentURL mediaRange=\"31488008-33619543\"/>\n                    <SegmentURL mediaRange=\"33619544-35705558\"/>\n                    <SegmentURL mediaRange=\"35705559-37818428\"/>\n                    <SegmentURL mediaRange=\"37818429-39977016\"/>\n                    <SegmentURL mediaRange=\"39977017-42150514\"/>\n                    <SegmentURL mediaRange=\"42150515-44298834\"/>\n                    <SegmentURL mediaRange=\"44298835-46008014\"/>\n                    <SegmentURL mediaRange=\"46008015-46143682\"/>\n                </SegmentList>\n            </Representation>\n        </AdaptationSet>\n        <AdaptationSet id=\"2\" contentType=\"audio\" selectionPriority=\"1000\">\n            <ContentProtection schemeIdUri=\"urn:mpeg:dash:mp4protection:2011\" cenc:default_KID=\"e41fd55b-2291-22cf-8d81-3e3a0baedb06\" value=\"cenc\"/>\n            <ContentProtection schemeIdUri=\"urn:uuid:edef8ba9-79d6-4ace-a3c8-27dcd51d21ed\" value=\"AmzMusic-2019\">\n                <cenc:pssh>AAAAs3Bzc2gAAAAA7e+LqXnWSs6jyCfc1R0h7QAAAJMiHGNpZDpmMDByMDJFZVh6em5qNGhLelhaSmxRPT04AFAAWAJqEUtBVEFOQV9DT05URU5UOlVTcloKEH9NK9NhHl8854+ISs12SZUSEOQf1VsikSLPjYE+Oguu2wYaIP4FzywwBaaYPH34rSoH2CwMKva/1F0wcLESYaBHHpOrIhCgtjAEZAe/CWBN6+WmLOWVKCA=</cenc:pssh>\n                <amz-music:groupId>KATANA_CONTENT:US</amz-music:groupId>\n                <amz-music:expires>2020-01-22T00:00:00Z</amz-music:expires>\n                <amz-music:masterKeyId>7F4D2BD3611E5F3CE78F884ACD764995</amz-music:masterKeyId>\n            </ContentProtection>\n            <SupplementalProperty schemeIdUri=\"urn:mpeg:mpegB:cicp:ProgramLoudness\" value=\"-10.0 LUFS\"/>\n            <SupplementalProperty schemeIdUri=\"amz-music:trackType\" value=\"SD\"/>\n            <SupplementalProperty schemeIdUri=\"urn:mpeg:dash:adaptation-set-switching:2016\" value=\"1\"/>\n            <SupplementalProperty schemeIdUri=\"urn:mpeg:mpegB:cicp:AnchorLoudness\" value=\"-7.4 LUFS\"/>\n            <Representation id=\"3\" qualityRanking=\"3\" codecs=\"opus\" audioSamplingRate=\"48000\" bandwidth=\"53513\" mimeType=\"audio/mp4\">\n                <AudioChannelConfiguration schemeIdUri=\"urn:mpeg:dash:23003:3:audio_channel_configuration:2011\" value=\"2\"/>\n                <BaseURL>https://d37b6sgey2y8gt.cloudfront.net/1d5482d6-7200000335449908/a27955d7-a97f-3983-97c5-0a948e6b9dbd.mp4?r=75e8534e-6083-4a33-9e95-e3c5bf1c9fdd&amp;rs=NA&amp;mt=US</BaseURL>\n                <SegmentList timescale=\"48000\" duration=\"480000\">\n                    <Initialization range=\"0-1019\"/>\n                    <SegmentURL mediaRange=\"1340-61595\"/>\n                    <SegmentURL mediaRange=\"61596-121731\"/>\n                    <SegmentURL mediaRange=\"121732-181867\"/>\n                    <SegmentURL mediaRange=\"181868-246056\"/>\n                    <SegmentURL mediaRange=\"246057-310245\"/>\n                    <SegmentURL mediaRange=\"310246-374434\"/>\n                    <SegmentURL mediaRange=\"374435-438623\"/>\n                    <SegmentURL mediaRange=\"438624-502812\"/>\n                    <SegmentURL mediaRange=\"502813-567001\"/>\n                    <SegmentURL mediaRange=\"567002-631190\"/>\n                    <SegmentURL mediaRange=\"631191-695379\"/>\n                    <SegmentURL mediaRange=\"695380-759568\"/>\n                    <SegmentURL mediaRange=\"759569-823757\"/>\n                    <SegmentURL mediaRange=\"823758-887946\"/>\n                    <SegmentURL mediaRange=\"887947-952135\"/>\n                    <SegmentURL mediaRange=\"952136-1016324\"/>\n                    <SegmentURL mediaRange=\"1016325-1080513\"/>\n                    <SegmentURL mediaRange=\"1080514-1144702\"/>\n                    <SegmentURL mediaRange=\"1144703-1208891\"/>\n                    <SegmentURL mediaRange=\"1208892-1273080\"/>\n                    <SegmentURL mediaRange=\"1273081-1337269\"/>\n                    <SegmentURL mediaRange=\"1337270-1401458\"/>\n                    <SegmentURL mediaRange=\"1401459-1465647\"/>\n                    <SegmentURL mediaRange=\"1465648-1480616\"/>\n                </SegmentList>\n            </Representation>\n            <Representation id=\"4\" qualityRanking=\"2\" codecs=\"opus\" audioSamplingRate=\"48000\" bandwidth=\"197652\" mimeType=\"audio/mp4\">\n                <AudioChannelConfiguration schemeIdUri=\"urn:mpeg:dash:23003:3:audio_channel_configuration:2011\" value=\"2\"/>\n                <BaseURL>https://d37b6sgey2y8gt.cloudfront.net/1d5482d6-7200000335449908/3a887953-9129-3958-9ee7-df2aa93f715c.mp4?r=75e8534e-6083-4a33-9e95-e3c5bf1c9fdd&amp;rs=NA&amp;mt=US</BaseURL>\n                <SegmentList timescale=\"48000\" duration=\"480000\">\n                    <Initialization range=\"0-1019\"/>\n                    <SegmentURL mediaRange=\"1340-241955\"/>\n                    <SegmentURL mediaRange=\"241956-482091\"/>\n                    <SegmentURL mediaRange=\"482092-722227\"/>\n                    <SegmentURL mediaRange=\"722228-966416\"/>\n                    <SegmentURL mediaRange=\"966417-1210605\"/>\n                    <SegmentURL mediaRange=\"1210606-1454794\"/>\n                    <SegmentURL mediaRange=\"1454795-1698983\"/>\n                    <SegmentURL mediaRange=\"1698984-1943172\"/>\n                    <SegmentURL mediaRange=\"1943173-2187361\"/>\n                    <SegmentURL mediaRange=\"2187362-2431550\"/>\n                    <SegmentURL mediaRange=\"2431551-2675739\"/>\n                    <SegmentURL mediaRange=\"2675740-2919928\"/>\n                    <SegmentURL mediaRange=\"2919929-3164117\"/>\n                    <SegmentURL mediaRange=\"3164118-3408306\"/>\n                    <SegmentURL mediaRange=\"3408307-3652495\"/>\n                    <SegmentURL mediaRange=\"3652496-3896684\"/>\n                    <SegmentURL mediaRange=\"3896685-4140873\"/>\n                    <SegmentURL mediaRange=\"4140874-4385062\"/>\n                    <SegmentURL mediaRange=\"4385063-4629251\"/>\n                    <SegmentURL mediaRange=\"4629252-4873440\"/>\n                    <SegmentURL mediaRange=\"4873441-5117629\"/>\n                    <SegmentURL mediaRange=\"5117630-5361818\"/>\n                    <SegmentURL mediaRange=\"5361819-5606007\"/>\n                    <SegmentURL mediaRange=\"5606008-5661296\"/>\n                </SegmentList>\n            </Representation>\n            <Representation id=\"5\" qualityRanking=\"1\" codecs=\"opus\" audioSamplingRate=\"48000\" bandwidth=\"325776\" mimeType=\"audio/mp4\">\n                <AudioChannelConfiguration schemeIdUri=\"urn:mpeg:dash:23003:3:audio_channel_configuration:2011\" value=\"2\"/>\n                <BaseURL>https://d37b6sgey2y8gt.cloudfront.net/1d5482d6-7200000335449908/9a223bf5-a59a-3f70-aedb-0d960b7843a1.mp4?r=75e8534e-6083-4a33-9e95-e3c5bf1c9fdd&amp;rs=NA&amp;mt=US</BaseURL>\n                <SegmentList timescale=\"48000\" duration=\"480000\">\n                    <Initialization range=\"0-1019\"/>\n                    <SegmentURL mediaRange=\"1340-402275\"/>\n                    <SegmentURL mediaRange=\"402276-802411\"/>\n                    <SegmentURL mediaRange=\"802412-1202547\"/>\n                    <SegmentURL mediaRange=\"1202548-1606736\"/>\n                    <SegmentURL mediaRange=\"1606737-2010925\"/>\n                    <SegmentURL mediaRange=\"2010926-2415114\"/>\n                    <SegmentURL mediaRange=\"2415115-2819303\"/>\n                    <SegmentURL mediaRange=\"2819304-3223492\"/>\n                    <SegmentURL mediaRange=\"3223493-3627681\"/>\n                    <SegmentURL mediaRange=\"3627682-4031870\"/>\n                    <SegmentURL mediaRange=\"4031871-4436059\"/>\n                    <SegmentURL mediaRange=\"4436060-4840248\"/>\n                    <SegmentURL mediaRange=\"4840249-5244437\"/>\n                    <SegmentURL mediaRange=\"5244438-5648626\"/>\n                    <SegmentURL mediaRange=\"5648627-6052815\"/>\n                    <SegmentURL mediaRange=\"6052816-6457004\"/>\n                    <SegmentURL mediaRange=\"6457005-6861193\"/>\n                    <SegmentURL mediaRange=\"6861194-7265382\"/>\n                    <SegmentURL mediaRange=\"7265383-7669571\"/>\n                    <SegmentURL mediaRange=\"7669572-8073760\"/>\n                    <SegmentURL mediaRange=\"8073761-8477949\"/>\n                    <SegmentURL mediaRange=\"8477950-8882138\"/>\n                    <SegmentURL mediaRange=\"8882139-9286327\"/>\n                    <SegmentURL mediaRange=\"9286328-9377456\"/>\n                </SegmentList>\n            </Representation>\n        </AdaptationSet>\n    </Period>\n</MPD>\n",
      "musicDashVersion": "SIREN_KATANA",
      "substituteAsin": "B07ZPBYSNN"
    }
  ]
}`

**Comment by Superhackman** [comment]
Delicate Taylor Swift 
Quality: FLAC 24 bits 44.1 kHz
link: https://d37b6sgey2y8gt.cloudfront.net/1d5482d6-7200000335449908/9c13109a-6231-3004-a10a-f81c488c9868.mp4

default_KID="e7cae012-8c5e-8514-6356-1dfae3f04b6f"

cenc:psshAAAAs3Bzc2gAAAAA7e+LqXnWSs6jyCfc1R0h7QAAAJMiHGNpZDpmMDByMDJFZVh6em5qNGhLelhaSmxRPT04AFAAWAJqEUtBVEFOQV9DT05URU5UOlVTcloKEH9NK9NhHl8854+ISs12SZUSEOfK4BKMXoUUY1Yd+uPwS28aIDerdLdweSmirTLORZyG2I2WXXI1jdmE0nQOCJBZ1Wi2IhASTqw02e7UpG/lA4pF20JBKCA=

**Comment by Superhackman** [comment]
at least amazon music provides a manifest with dash format, but it hurts that it is not compatible with some widevine l3 key generator, they should make it compatible

**Comment by astravaganza** [comment]
> they should make it compatible
what are you, insane?
