### ISSUE TITLE
manifest.mpd with multiple periods only download last period

### ISSUE THREAD

**Issue by Byter432** [parnexcodes/widevine-L3-WEB-DL-Script#51]
Working fine but with 1 issue:

Is there a way to make sure it grabs all periods from the manifest.mpd, it only seems to grab the last period.
There is allready the same question but no solution given.
Can somebody help me to configure webdl.py or keys.json or manifest.mpd?

Thanks in advance.

**Comment by Essam3152** [comment]
You might need to post the link of the site and a link for that mpd so the members could try to find a fix using yt-dlp or any other programs, or finding an alternative method for downloading the video from this site.

**Comment by Byter432** [comment]
https://dcs-vod.apis.anvato.net/vod/p/manifest.mpd?encp=STqJ2QdUL5FB3VF4SWNikA:qZF3hP3KIhxm31yVwdsBg846LqiqV8cXY6-aQfENBaG5C_7kDW7byHmKaFo4Jp_2TUC9NmMtNaqSLP0MtBBltesTpD6EMYFZA0CkZYTQcqic_32ojqU4sdhfG1JpZjrxNLhnIr0ZvTm1LeTfFpwwBuFa4gFJ_w3mzNr1rsMwER2pUVlasCdsDd2O4gt06MNqSC1szUZOySjMYZb4gJ02M-E3hgARZRBjLKg9MYsoIxdYpDHUj8vkK9pF7d1WaBOqFV42SFeeq08serrWiG-cz2NKFW1L2Jv6s2qsBONbGe9aiQsn1ITXGW4_25i84RExfDGNYygwp77a-mUMJsN1sVIp6PVLqUNNC5S8EB89acdJK-YsyIYAC3xiBEOxVKM0v5c_Kr9PC3Z4xFWGWifxJLW_lk633G1BCsMv5ElZk0OOW9mEAkHWQ2VZ8zr3CfHqtPG241pKy6EANZVPiGKZGCjSX9Uj0QLa4HlzhDIh0eg&anvtrid=6419237fa40d3d3976a162b96268b444&anvauth=tb=0~te=1631429331~sgn=1f1b7505b6e5b758513f8f8d027e0624cd74647d58ec209aeb2b99728cbfd592&t=1631429241

I have 5 keys.

Webdl.py only gives me the second part of the video.

Thanks

**Comment by Essam3152** [comment]
From which site this mpd?:  I mean put a link like.

https://www.primevideo.com/region/eu/

**Comment by Byter432** [comment]
https://vtm.be/vtmgo/afspelen/e2b1d833a-023b-478c-b41a-6ba84375abe8

Region Belgium

**Comment by Essam3152** [comment]
Use this modified version of the script widevine-L3-WEB-DL-Script, it originally modified by @JudgeUAu I just added to it the latest version of N_m3u8DL-CLI

https://github.com/nilaoda/N_m3u8DL-CLI/actions/runs/1202972652

and changed the audio to aac to work with the site vtmgo, just run download.bat and the program will download the video and the audio and decrypts and merges them, I tested it by myself and it works just fine (keys.json for the video is included with the script).

[widevine-L3-WEB-DL-Script-vtmgo.zip](https://github.com/parnexcodes/widevine-L3-WEB-DL-Script/files/7149486/widevine-L3-WEB-DL-Script-vtmgo.zip)

**Comment by Byter432** [comment]
Thank you very very much.

It's working like a charm.

Greatz
