### ISSUE TITLE
List qualities for a video?

### ISSUE THREAD

**Issue by EliteAppleHacks** [parnexcodes/widevine-L3-WEB-DL-Script#53]
I tried changing some settings to get lower quality video formats for ytdlp but all say 

'WARNING: --downloader-args given without specifying name. The arguments will be given to all external downloaders
[generic] 9477e424-2212-43b4-80f2-71f315862223_corrected: Requesting header
WARNING: [generic] Falling back on generic information extractor.
[generic] 9477e424-2212-43b4-80f2-71f315862223_corrected: Downloading webpage
[generic] 9477e424-2212-43b4-80f2-71f315862223_corrected: Extracting information
ERROR: Requested format is not available'

Is there a way to view other resolution and select a generic resolution size?

**Comment by parnexcodes** [comment]
-F

**Comment by EliteAppleHacks** [comment]
Figured out the implimentation
