### ISSUE TITLE
Decryption seems good but is failed

### ISSUE THREAD

**Issue by manzing** [parnexcodes/widevine-L3-WEB-DL-Script#55]
Hi,

I tested the script with a primevideo vid and the full process is OK without any error.

But the MKV file is unreadable using VLC, and mediainfo displays format and codec identifier as V_QUICKTIME.
I checked encrypted file and format is AVC. Decrypted video file is AVC but unreadable too, guess that decryption failed.

Why has this format change with mkvmerge ? I cannot find any setting to modify in the script that would affect this behavior.

![quicktime](https://user-images.githubusercontent.com/2737265/134796589-34fa3fb9-b5bd-448d-8189-78a07b4bdcd1.jpg)
Any idea ?
Thanks,

**Comment by acocalypso** [comment]
Same here with Prime video sometimes

**Comment by manzing** [comment]
Always happen for me.
I just found out what occurs : decryption fails because it uses a bad key.
I was able to succesfully decrypt a file manually using mp4decrypt.
Key.txt has 3 keys inside, if I don't use the good one, video is unreadble too.

Seems like the script does not use the good key between the 3 provided by key.txt.

**Comment by manzing** [comment]
OK, I was using "method-2" script, I just tested with main method, with json file and its fine.
