### ISSUE TITLE
Hello, I want to ask a question. Can I download this?

### ISSUE THREAD

**Issue by ali617768987** [parnexcodes/widevine-L3-WEB-DL-Script#58]
Hi, I would like to ask whether video OTT like this can download it through your widevine-L3-WEB-DL-Script? I tried to download MPD but it didn't work.

https://video.friday.tw/drama/detail/1503

**Comment by ali617768987** [comment]
the VPN is TAIWAN

**Comment by arasad24** [comment]
if you get mpd link from this ott side I think think script may work

**Comment by ali617768987** [comment]
> if you get mpd link from this ott side I think think script may work

![image](https://user-images.githubusercontent.com/77323405/135700215-2f128adf-0520-40d9-80be-ca24add791a7.png)

I've tried this many times. It doesn't seem to work.
