### ISSUE TITLE
Audio file decrypted as a 0KB File

### ISSUE THREAD

**Issue by vipul-ramachandran** [parnexcodes/widevine-L3-WEB-DL-Script#67]
Hello, I am downloading a file from site I am subscribed to, with the contents of the keys.json file as below in this issue. 
I tried running the script but got an error message: 

```
Starting Decryption
[====================================================================================================] 100 %
Decryption took: 00 Seconds
Decrypted successfully
Merging .....
mkvmerge v57.0.0 ('Till The End') 64-bit
Error: The type of file 'decrypted.m4a' could not be recognized.

All Done ..... 
```
So, when I checked, the m4a file after decryption has a 0KB file size, although the decryption of the video was done successfully (I am able to play it as well,  obviously without sound!). 

Content of keys.json file: 
```
[
  {
    "mpd_url": "https://d3irpeu90xxc4b.cloudfront.net/cmaf/s1siddharthmenon01/episodes/introduction_e01/introduction_e01.mpd"
  },
  {
    "kid": "c8c8f8af190b4d8d870154300710907a",
    "hex_key": "aadcda9d56a75082418de25bba43df18"
  }
]
```

Is it a bug?

**Comment by Essam23** [comment]
In the folder "binaries" replace mp4decrypt_new.exe with this one, I tested it and worked.

[mp4decrypt_new.zip](https://github.com/parnexcodes/widevine-L3-WEB-DL-Script/files/7400199/mp4decrypt_new.zip)

**Comment by vipul-ramachandran** [comment]
Wow!!! that did indeed worked. Thanks for the fix. I will close this issue!
