### ISSUE TITLE
amz/peacock 

### ISSUE THREAD

**Issue by techno-arch** [parnexcodes/widevine-L3-WEB-DL-Script#7]
after changing the lines of code to suit the website im trying to grab from i get some errors 

ERROR: aria2c exited with code 22
WARNING: --downloader-args given without specifying name. The arguments will be given to all external downloaders
[generic] aeeb5080-afa8-4260-9223-fe8616d8b885_corrected: Requesting header
WARNING: [generic] Falling back on generic information extractor.
[generic] aeeb5080-afa8-4260-9223-fe8616d8b885_corrected: Downloading webpage
[generic] aeeb5080-afa8-4260-9223-fe8616d8b885_corrected: Extracting information
[info] aeeb5080-afa8-4260-9223-fe8616d8b885_corrected: Downloading 1 format(s): video=2400000-10
[download] Destination: encrypted.mp4

08/02 13:39:08 [ERROR] CUID#7 - Download aborted. URI=https://s3-iad-2.cf.dash.row.aiv-cdn.net/dm/2$It_EtQAh4NXqbiFA9DC6xo8Syc4~/1@593bac3294aa0ee458b5359231f60d7b/2d15/87b3/2647/4dbd-a801-d72f23afb743/2d15/87b3/2647/4dbd-a801-d72f23afb743/aeeb5080-afa8-4260-9223-fe8616d8b885_video_9.mp4
Exception: [AbstractCommand.cc:351] errorCode=22 URI=https://s3-iad-2.cf.dash.row.aiv-cdn.net/dm/2$It_EtQAh4NXqbiFA9DC6xo8Syc4~/1@593bac3294aa0ee458b5359231f60d7b/2d15/87b3/2647/4dbd-a801-d72f23afb743/2d15/87b3/2647/4dbd-a801-d72f23afb743/aeeb5080-afa8-4260-9223-fe8616d8b885_video_9.mp4
  -> [HttpSkipResponseCommand.cc:240] errorCode=22 The response status is not successful. status=403

aria2 will resume download if the transfer is restarted.
If there are any errors, then see the log file. See '-l' option in help/man page for details.

ERROR: aria2c exited with code 22

this happens with both amz and peackock

**Comment by parnexcodes** [comment]
Check if you're able to download this file from your browser.

**Comment by techno-arch** [comment]
i copied the link from the cmd and tried to download it via my browser and i still got the same thing

**Comment by parnexcodes** [comment]
Send me the mpd link along with keys.json if you can.

**Comment by techno-arch** [comment]
[keys (4).zip](https://github.com/parnexcodes/widevine-L3-WEB-DL-Script/files/6920613/keys.4.zip)

i dont have the og json but i get the same issues with this and it is from the same video also the .mpd file is in the zip with the keys

**Comment by techno-arch** [comment]
i found out how you are supposed to web-dl from amz do you think there's any way to implement this in your script/extension   https://lbry.tv/@cryptic:6/mp4decryptgui

**Comment by parnexcodes** [comment]
> 
> 
> [keys (4).zip](https://github.com/parnexcodes/widevine-L3-WEB-DL-Script/files/6920613/keys.4.zip)
> 
> i dont have the og json but i get the same issues with this and it is from the same video also the .mpd file is in the zip with the keys

The mpd is the second one , change `json_mpd_url = config[0]['mpd_url']` to `json_mpd_url = config[1]['mpd_url']`

**Comment by parnexcodes** [comment]
I tried it , the mpd url seems to be the second one.
You can also make the url yourself by removing the above part and appending the below mentioned part (check image)
https://i.imgur.com/pWih28B.png

**Comment by parnexcodes** [comment]
I suggest using this branch : https://github.com/parnexcodes/widevine-L3-WEB-DL-Script/tree/method-2
