### ISSUE TITLE
How to do on N3tflix?

### ISSUE THREAD

**Issue by jvsdr** [parnexcodes/widevine-L3-WEB-DL-Script#70]
Is possible to use this script to get n3tflix stuff?

**Comment by projectnaked** [comment]
Use This Script https://github.com/Essam3152/Netflix-videos-downloader/archive/refs/heads/main.zip 

its easy to use and u can download full seasons

**Comment by jvsdr** [comment]
> Use This Script https://github.com/Essam3152/Netflix-videos-downloader/archive/refs/heads/main.zip
> 
> its easy to use and u can download full seasons

Thank you dude, I will test!
