### ISSUE TITLE
Not Decrypting....

### ISSUE THREAD

**Issue by Nasimaktar99** [parnexcodes/widevine-L3-WEB-DL-Script#77]
<img width="956" alt="Screenshot 2021-10-31 145503" src="https://user-images.githubusercontent.com/67604361/139576168-91ee386c-90a7-48ff-b08a-bcfb34f8f036.png">
 Unable to decrypt ..
'D:\Testing\widevine-L3-WEB-DL-Script-main' is not recognized as an internal or external command,
operable program or batch file.

**Comment by Rider143** [comment]
Give entire video name as shown in your cmd prompt, just not 5 or 8
