### ISSUE TITLE
Pywidevine Disney+ Free4ALL

### ISSUE THREAD

**Issue by vatoloco77** [parnexcodes/widevine-L3-WEB-DL-Script#81]
SCript 4 all if someone fix pls send me here vatoslocosmx@protonmail.com or upload here on gh.

https://1fichier.com/?wi5wt4j8atku0o66kw2j

**Comment by loveyoursupport** [comment]
does anyone have hbo max tool?

**Comment by BeeMuffins** [comment]
Anyone know how to fix:  ImportError: cannot import name 'output' from 'svtplay_dl.utils.output'

**Comment by Essam3152** [comment]
@BeeMuffins `pip install svtplay-dl==3.7`

**Comment by NiKoCZ89** [comment]
> 
> 
> @BeeMuffins `pip install svtplay-dl==3.7`

This disney script don't work anyway, or someone can fix already ? can share ? Pls.

**Comment by BeeMuffins** [comment]
> @BeeMuffins `pip install svtplay-dl==3.7`

Thank you very much. I had a newer version installed.

**Comment by Essam3152** [comment]
@vatoloco77 Here is the script fixed (not by me), but it most likely will need more fixes and enhancements, I added an old cdm, it downloads the audio and subtitles for most of the contents without any problems and it can decrypt some videos in 480p, I added how.to.use.txt for anyone wants to download the audio and subtitles with it.

https://mega.nz/file/V013lSJB#m1Lc_QnKz2iwXo8HNujn0nzqQlgojK7KILaaPzHAvUg

**Comment by vatoloco77** [comment]
> @vatoloco77 Here is the script fixed (not by me), but it most likely will need more fixes and enhancements, I added an old cdm, it downloads the audio and subtitles for most of the contents without any problems and it can decrypt some videos in 480p, I added how.to.use.txt for anyone wants to download the audio and subtitles with it.
> 
> https://mega.nz/file/V013lSJB#m1Lc_QnKz2iwXo8HNujn0nzqQlgojK7KILaaPzHAvUg

thank you so much mate! it works even 720p i love u! lol ;)

maybe u have same script with amazon ? i have amazon tool but stopped working maybe api problem idk

i have hulu pywidevine working 

just contact vatoslocosmx@protonmail.com if u want

**Comment by Essam3152** [comment]
@vatoloco77 The Amazon script most likely a cdm problem, it needs cdm l1 not revoked.

**Comment by vatoloco77** [comment]
> @vatoloco77 The Amazon script most likely a cdm problem, it needs cdm l1 not revoked.

then why with this script i can download fhd from amazon ?

**Comment by Essam3152** [comment]
@vatoloco77 Do you have a working cdm l1?
