### ISSUE TITLE
script doesn't pick best audio

### ISSUE THREAD

**Issue by NiKoCZ89** [parnexcodes/widevine-L3-WEB-DL-Script#84]
Hi
anyone know how to fix this ? this script always download low bitrate audio not "ba" 

audio_eng_1=224000 m4a audio only     |  224k dash  |                   ec-3      224k 48000Hz [en], DASH audio, m4a_dash
audio_eng_2=384000 m4a audio only     |  384k dash  |                   ac-3      384k 48000Hz [en], DASH audio, m4a_dash
audio_eng=96000    m4a audio only     |   96k dash  |                   mp4a.40.2  96k 48000Hz [en], DASH audio, m4a_dash

script alwys pick this one audio_eng=96000 instead of audio_eng_2=384000

site viaplay

**Comment by ye74** [comment]
Hello, did you get it working for viaplay?
I can't seem to get it working
I'll send you 10$ if you explain ;)

**Comment by dr0ops** [comment]
Try changing (adding) into the script :

if audio_id == "" :
      audio_id = "(ba)[tbr=384][acodec=ac-3]

That will make it choose : 
      audio_eng_2=384000 m4a audio only | 384k dash | ac-3 384k 48000Hz [en], DASH audio, m4a_dash

or just add this instead if u want it to work even better when using it for ViAPLAY : 

if audio_id == "" :
      audio_id = "(ba)[language*=sv][tbr=384][acodec=ac-3] / (ba)[language*=fi][tbr=384][acodec=ac-3] / (ba)[language*=da][tbr=384][acodec=ac-3] / (ba)[language*=no][tbr=384][acodec=ac-3] / (ba)[language*=en][tbr=384][acodec=ac-3] / (ba)[language*=sv][tbr=224][acodec=ac-3] / (ba)[language*=fi][tbr=224][acodec=ac-3] / (ba)[language*=da][tbr=224][acodec=ac-3] / (ba)[language*=no][tbr=224][acodec=ac-3] / (ba)[language*=en][tbr=224][acodec=ac-3] / (ba)[language*=sv][tbr=128][acodec=ac-3] / (ba)[language*=fi][tbr=128][acodec=ac-3] / (ba)[language*=da][tbr=128][acodec=ac-3] / (ba)[language*=no][tbr=128][acodec=ac-3] / (ba)[language*=en][tbr=128][acodec=ac-3] / (ba)"

Happy ripping 😄

**Comment by ye74** [comment]
> Try changing (adding) into the script :
> 
> if audio_id == "" : audio_id = "(ba)[tbr=384][acodec=ac-3]
> 
> That will make it choose : audio_eng_2=384000 m4a audio only | 384k dash | ac-3 384k 48000Hz [en], DASH audio, m4a_dash
> 
> or just add this instead if u want it to work even better when using it for ViAPLAY :
> 
> if audio_id == "" : audio_id = "(ba)[language*=sv][tbr=384][acodec=ac-3] / (ba)[language*=fi][tbr=384][acodec=ac-3] / (ba)[language*=da][tbr=384][acodec=ac-3] / (ba)[language*=no][tbr=384][acodec=ac-3] / (ba)[language*=en][tbr=384][acodec=ac-3] / (ba)[language*=sv][tbr=224][acodec=ac-3] / (ba)[language*=fi][tbr=224][acodec=ac-3] / (ba)[language*=da][tbr=224][acodec=ac-3] / (ba)[language*=no][tbr=224][acodec=ac-3] / (ba)[language*=en][tbr=224][acodec=ac-3] / (ba)[language*=sv][tbr=128][acodec=ac-3] / (ba)[language*=fi][tbr=128][acodec=ac-3] / (ba)[language*=da][tbr=128][acodec=ac-3] / (ba)[language*=no][tbr=128][acodec=ac-3] / (ba)[language*=en][tbr=128][acodec=ac-3] / (ba)"
> 
> Happy ripping 😄

How to pick the best quality?

**Comment by dr0ops** [comment]
Use : [https://github.com/yt-dlp/yt-dlp#format-selection](url)
