### ISSUE TITLE
Where is the mistake ?

### ISSUE THREAD

**Issue by Amb33r** [parnexcodes/widevine-L3-WEB-DL-Script#89]
@Essam3152
Help, buddy, where's the problem again?
Thank you

- [ ] [
  {
    "mpd_url": "https://redirector.redefine.pl/vm2dash/7041a70352dd0c7177e72fd2d535fb46ea0206cf/manifest.mpd"
  },
  {
    "kid": "28258b9ff8f4c00b3c6400000055df08",
    "hex_key": "edc194782a9ababd804900ed9d6a9aec"
  }
]

![image](https://user-images.githubusercontent.com/70627077/142374094-17b0f626-04d2-479f-8e17-e69a6eca8493.png)

**Comment by projectnaked** [comment]
check if there is any SPACE in the folder name  F:\VOD

**Comment by Amb33r** [comment]
I moved to another disk, changed the name and it's ok
Thanks

**Comment by Amb33r** [comment]
Another problem, but already a different .mpd

![image](https://user-images.githubusercontent.com/70627077/142403435-cc7293de-4187-42eb-8459-63e8d3abb140.png)

- [ ] [
  {
    "mpd_url": "https://vod24-dash-cdn1-vp-cdn-viaplay-tv.akamaized.net/cb42d88/20678957-1626045091744.ism/index.mpd"
  },
  {
    "kid": "08cd1d3b68225da2b1670f1615cd21b1",
    "hex_key": "2ebec180a719c01d1883c2f82ad52388"
  },
  {
    "kid": "65e220dbc709515ea1949c017f5e30ab",
    "hex_key": "d240426852a620d861268bce77ebc09e"
  },
  {
    "kid": "269c526cc334535f8b1b71fa514ca0fb",
    "hex_key": "72b0e5f15938ec9df8f8d3cdf8fe66b0"
  }
]

**Comment by projectnaked** [comment]
> Another problem, but already a different .mpd
> 
> ![image](https://user-images.githubusercontent.com/70627077/142403435-cc7293de-4187-42eb-8459-63e8d3abb140.png)
> 
> * [ ]  [
>   {
>   "mpd_url": "https://vod24-dash-cdn1-vp-cdn-viaplay-tv.akamaized.net/cb42d88/20678957-1626045091744.ism/index.mpd"
>   },
>   {
>   "kid": "08cd1d3b68225da2b1670f1615cd21b1",
>   "hex_key": "2ebec180a719c01d1883c2f82ad52388"
>   },
>   {
>   "kid": "65e220dbc709515ea1949c017f5e30ab",
>   "hex_key": "d240426852a620d861268bce77ebc09e"
>   },
>   {
>   "kid": "269c526cc334535f8b1b71fa514ca0fb",
>   "hex_key": "72b0e5f15938ec9df8f8d3cdf8fe66b0"
>   }
>   ]

its worked fine for me

**Comment by Amb33r** [comment]
Which webdl.py did you use? can you send it

**Comment by projectnaked** [comment]
i used the original one without any modification, but i had the same problem in the web-dl peacock script i think there is something cached and you need to clear it

**Comment by ampersand88** [comment]
> its worked fine for me

how does the script handle there being three kid/key pairs? from what I can see it's meant for only one? I've tried downloading from amazon and I get garbled video and audio.
